# Generated by Django 5.1.3 on 2024-11-17 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
