# Generated by Django 5.1.3 on 2024-11-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense'), ('Savings', 'Savings'), ('Investment', 'Investment'), ('Debt', 'Debt')], max_length=10),
        ),
    ]
